"use client";

import { useEffect, useState } from "react";
type Props={onActiveRide?:(rideId:string|null)=>void};

export default function BasgoCourierPanel({onActiveRide}:Props){
 const [driver,setDriver]=useState<any>(null),[phone,setPhone]=useState(""),[password,setPassword]=useState(""),[requests,setRequests]=useState<any[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[active,setActive]=useState<any>(null),[completeBusy,setCompleteBusy]=useState(false),[onlineBusy,setOnlineBusy]=useState(false);
 const load=async()=>{const me=await fetch("/api/auth/me").then(r=>r.json()).catch(()=>({}));if(me.driver){setDriver(me.driver);const r=await fetch("/api/basgo/courier/requests");const d=await r.json();if(r.ok)setRequests(Array.isArray(d.requests)?d.requests:[])}};
 useEffect(()=>{load()},[]);
 const login=async()=>{setError("");setBusy(true);try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Не удалось войти");setDriver(d.driver);await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка входа")}finally{setBusy(false)}};
 const setOnline=async(online:boolean)=>{setError("");setOnlineBusy(true);try{const r=await fetch("/api/basgo/courier/online",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({online})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Не удалось изменить статус");setDriver((x:any)=>({...x,...d.driver,is_online:online}));if(online)await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка статуса")}finally{setOnlineBusy(false)}};
 const accept=async(rideId:string,price:number)=>{setError("");setBusy(true);try{const r=await fetch("/api/basgo/courier/accept",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rideId,agreedPrice:price})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Не удалось принять заказ");setActive(d.order);onActiveRide?.(rideId);await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}};
 const complete=async()=>{if(!active?.id)return;setError("");setCompleteBusy(true);try{const r=await fetch("/api/basgo/courier/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rideId:active.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Не удалось завершить заказ");setActive(d.order);onActiveRide?.(null);await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка завершения")}finally{setCompleteBusy(false)}};
 if(!driver)return <div className="basgo-courier-login"><div className="basgo-courier-login-head"><b>Регистрация / вход исполнителя</b><span>Телефон и пароль открывают профиль, линию и заказы.</span></div><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Телефон"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Пароль"/>{error&&<div className="basgo-order-error">{error}</div>}<button type="button" className="basgo-primary" disabled={busy} onClick={login}>{busy?"Входим…":"Войти как исполнитель"}</button></div>;
 const lineStyle:any={border:0,borderRadius:999,padding:"7px 10px",fontSize:9,fontWeight:800,cursor:"pointer",background:driver.is_online?"#163b2b":"#252e38",color:driver.is_online?"#8de0b4":"#aab5c4"};
 return <div className="basgo-courier-panel">
  <div className="basgo-courier-user"><div><b>{driver.name}</b><span>{driver.phone}{driver.car?" · "+driver.car:""}{driver.plate?" · "+driver.plate:""}</span></div><button type="button" style={lineStyle} disabled={onlineBusy} onClick={()=>setOnline(!driver.is_online)}>{onlineBusy?"…":driver.is_online?"ОНЛАЙН · ВЫЙТИ С ЛИНИИ":"ОФФЛАЙН · ВЫЙТИ НА ЛИНИЮ"}</button></div>
  <div className="basgo-courier-list"><b>Доступные поручения</b>{requests.filter(x=>x.status==="pending").slice(0,8).map(x=><div className="basgo-courier-request" key={x.id}><div><strong>{x.message||"Поручение BASGO"}</strong><span>{x.pickup||"Точка забора"} → {x.destination}</span><small>{Number(x.offer_price||0).toLocaleString("ru-RU")} ₸ · {x.payment_method}</small></div><button type="button" onClick={()=>accept(x.id,Number(x.offer_price||0))} disabled={busy||!driver.is_online}>Принять</button></div>)}{!requests.some(x=>x.status==="pending")&&<span className="basgo-muted">Новых поручений пока нет.</span>}</div>
  {active?<div className="basgo-active-order"><b>Активный заказ</b><span>{active.id}</span><small>{active.status} · GPS передаётся только для активного заказа</small>{active.status!=="completed"?<button type="button" className="basgo-primary" disabled={completeBusy} onClick={complete}>{completeBusy?"Завершаем…":"Доставил / завершить заказ"}</button>:<button type="button" className="basgo-secondary" onClick={()=>{setActive(null);onActiveRide?.(null)}}>Закрыть заказ</button>}</div>:null}
  {error&&<div className="basgo-order-error">{error}</div>}
 </div>;
}