"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, LogOut, MapPin, PackageCheck, RefreshCw, ShieldCheck, Truck, WalletCards } from "lucide-react";

type Dashboard={stats:any;couriers:any[];orders:any[];settings:any};
const money=(n:number)=>`${Number(n||0).toLocaleString("ru-RU")} ₸`;
const statusText=(s:string)=>({pending:"Ищем курьера",accepted:"Принят",in_progress:"В пути",picked_up:"Забрал",completed:"Доставлен"} as any)[s]||s;

export default function BasgoAdminPage(){
 const [key,setKey]=useState(""),[authorized,setAuthorized]=useState(false),[data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[commission,setCommission]=useState("0");
 const load=async()=>{const r=await fetch("/api/basgo/admin/dashboard",{cache:"no-store"}),d=await r.json();if(!r.ok){setAuthorized(false);if(r.status!==401)setError(d.error||"Админка не настроена");return}setAuthorized(true);setData(d);setCommission(String(d.settings?.commission_percent??0));setError("")};
 useEffect(()=>{load()},[]); useEffect(()=>{if(!authorized)return;const i=window.setInterval(load,8000);return()=>window.clearInterval(i)},[authorized]);
 const login=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/basgo/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key})}),d=await r.json();if(!r.ok)throw new Error(d.error||"Неверный ключ");setAuthorized(true);await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка входа")}finally{setBusy(false)}};
 const logout=async()=>{await fetch("/api/basgo/admin/logout",{method:"POST"});setAuthorized(false);setData(null)};
 const save=async()=>{const v=Number(commission);if(!Number.isFinite(v)||v<0||v>100){setError("Комиссия: от 0 до 100%");return}const r=await fetch("/api/basgo/admin/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({commission:v})}),d=await r.json();if(!r.ok){setError(d.error||"Не удалось сохранить");return}await load()};
 const revenue=data?.stats.revenue_completed||0,rate=Number(commission)||0,commissionAmount=revenue*rate/100,payout=revenue-commissionAmount;
 if(!authorized)return <main style={S.shell}><section style={S.login}><div style={S.logo}>BAS<span>GO</span> <small>ADMIN</small></div><ShieldCheck size={40}/><h1>Админ-панель</h1><p>Заказы, курьеры, онлайн, GPS, заработок и выплаты.</p><input style={S.input} value={key} onChange={e=>setKey(e.target.value)} placeholder="Ключ администратора" type="password" onKeyDown={e=>{if(e.key==="Enter")login()}}/>{error&&<div style={S.error}>{error}</div>}<button style={S.primary} disabled={busy||!key} onClick={login}>{busy?"Проверяем…":"Войти"}</button><small style={S.muted}>Ключ не хранится в браузерном коде.</small></section></main>;
 return <main style={S.shell}><section style={S.app}><header style={S.header}><div><div style={S.logo}>BAS<span>GO</span> <small>ADMIN</small></div><div style={S.muted}>Центр управления доставкой</div></div><div style={{display:"flex",gap:8}}><button style={S.icon} onClick={load}><RefreshCw size={17}/></button><button style={S.icon} onClick={logout}><LogOut size={17}/></button></div></header>
 <div style={S.grid}><Stat icon={<PackageCheck/>} label="Все заказы" value={data?.stats.orders_total}/><Stat icon={<Activity/>} label="Активные" value={data?.stats.orders_active}/><Stat icon={<Truck/>} label="Курьеры онлайн" value={`${data?.stats.couriers_online}/${data?.stats.couriers_total}`}/><Stat icon={<WalletCards/>} label="Оборот" value={money(revenue)}/></div>
 <section style={S.finance}><div><span>Комиссия BASGO</span><b>{money(commissionAmount)}</b></div><div><span>К выплате курьерам</span><b>{money(payout)}</b></div><label>Ставка <input style={S.smallInput} value={commission} onChange={e=>setCommission(e.target.value)} inputMode="decimal"/> % <button style={S.smallBtn} onClick={save}>Сохранить</button></label></section>
 <section style={S.section}><h2>Курьеры сейчас</h2>{data?.couriers.map(c=><div style={S.row} key={c.id}><div style={S.avatar}>{String(c.name||"?").slice(0,1).toUpperCase()}</div><div style={{flex:1}}><b>{c.name||"Без имени"}</b><span style={S.sub}>{c.phone} · {c.orders_count} заказов · заработок {money(c.earnings)}</span>{c.latitude&&c.longitude?<span style={S.sub}><MapPin size={13}/> {Number(c.latitude).toFixed(5)}, {Number(c.longitude).toFixed(5)} · {c.last_location_at?new Date(c.last_location_at).toLocaleString("ru-RU"):"GPS нет"}</span>:<span style={S.sub}>Местоположение не передаётся</span>}</div><span style={{...S.badge,...(c.is_online?S.online:S.offline)}}>{c.is_online?"ОНЛАЙН":"ОФФЛАЙН"}</span></div>)}</section>
 <section style={S.section}><h2>Последние заказы</h2>{data?.orders.slice(0,50).map(o=><div style={S.order} key={o.id}><div><b>{String(o.id).slice(0,8).toUpperCase()}</b><span style={S.sub}>{o.pickup||"—"} → {o.destination||"—"}</span><span style={S.sub}>{o.driver_name||"Курьер не назначен"} · {o.passenger_phone||"телефон не указан"}</span></div><div style={{textAlign:"right"}}><b>{money(o.agreed_price||o.offer_price||0)}</b><span style={S.status}>{statusText(o.status)}</span></div></div>)}</section>
 </section></main>;
}
function Stat({icon,label,value}:{icon:any;label:string;value:any}){return <div style={S.stat}><div style={S.statIcon}>{icon}</div><span>{label}</span><b>{value}</b></div>}
const S:any={shell:{minHeight:"100vh",background:"#080b10",color:"#f7f8fa",padding:20,fontFamily:"Inter,system-ui,sans-serif"},app:{maxWidth:1100,margin:"0 auto"},login:{maxWidth:430,margin:"8vh auto",background:"#111720",border:"1px solid #27303b",borderRadius:28,padding:32,display:"flex",flexDirection:"column",gap:14,boxShadow:"0 20px 80px rgba(0,0,0,.35)"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:22},logo:{fontWeight:900,fontSize:24},muted:{color:"#8e99a8",fontSize:13},input:{background:"#0c1118",border:"1px solid #2a3440",borderRadius:14,padding:"14px 16px",color:"white",fontSize:16},primary:{border:0,borderRadius:14,padding:"14px 18px",background:"#d9ff3f",color:"#101400",fontWeight:800,fontSize:15},icon:{border:"1px solid #2a3440",background:"#111720",color:"white",borderRadius:12,padding:10},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12},stat:{background:"#111720",border:"1px solid #202a35",borderRadius:20,padding:18,display:"flex",flexDirection:"column",gap:7},statIcon:{color:"#d9ff3f"},finance:{marginTop:14,background:"#111720",border:"1px solid #202a35",borderRadius:20,padding:18,display:"flex",gap:24,alignItems:"center",flexWrap:"wrap"},section:{marginTop:16,background:"#111720",border:"1px solid #202a35",borderRadius:20,padding:18},row:{display:"flex",gap:12,alignItems:"center",padding:"13px 0",borderBottom:"1px solid #202a35"},order:{display:"flex",justifyContent:"space-between",gap:12,padding:"14px 0",borderBottom:"1px solid #202a35"},avatar:{width:38,height:38,borderRadius:12,background:"#202a35",display:"grid",placeItems:"center",fontWeight:900},sub:{display:"block",color:"#8e99a8",fontSize:12,marginTop:4},badge:{fontSize:10,fontWeight:900,borderRadius:999,padding:"7px 9px"},online:{background:"#d9ff3f",color:"#111"},offline:{background:"#252d36",color:"#9aa5b3"},status:{display:"block",color:"#d9ff3f",fontSize:11,marginTop:5},smallInput:{width:62,background:"#0c1118",border:"1px solid #2a3440",color:"white",borderRadius:8,padding:7},smallBtn:{marginLeft:8,border:0,borderRadius:8,padding:"7px 10px",background:"#26313d",color:"white"},error:{background:"#3b1820",color:"#ffb4c0",borderRadius:12,padding:10,fontSize:13}};
